<?php

foreach ($response as $key => $value) {
?>
    <form action="weather" method="POST">
        <div class="card" style="width: 50rem;">
            <div class="card-body">
                <h5 class="card-title"><?php echo $value['id'] ?>
                    <?php echo $value['name'] ?> <?php echo $value['region'] ?>  <button type="submit" class="border-0 bg-white text-primary" value="<?php echo $value['name'] ?>" name="getinfo">GET INFO</button> </h5>

            </div>
        </div>
    </form>
<?php
    // echo $k . ' => ' . $v;
    // echo '<br>';
}







?>